### ISSUE TITLE
version

### ISSUE THREAD

**Issue by Hunlongyu** [aarmn/negahban#3]
![image](https://github.com/aarmn/negahban/assets/15273630/62b7c756-e0f4-4214-82c5-946f967065d2)
![image](https://github.com/aarmn/negahban/assets/15273630/3216f56d-0444-48bd-b9a4-953b529b687e)

**Comment by aarmn** [comment]
Thanks for the reports, Ill address these issues ASAP

**Comment by aarmn** [comment]
![image](https://github.com/aarmn/negahban/assets/29726901/bfea8067-6c22-48ad-8d9b-724634763a93)
As you can see, the version 0.3.0 was yanked that's why its not synced in crates.io, but because lib.rs listed the minor version changes, without regards to yanks, you can see version 0.3.0 there.

I don't know the exact difference of these two websites purpose; but I'll always check updates in crates.io
